
def encodeConfigs(configs):
    return [
        configs['sim time settings']['time step'],
        configs['sim time settings']['total time'],
        configs['sim time settings']['sampling rate'],
        configs['general options']['customized ion profile']['extracellular Na+ concentration'],
        configs['general options']['customized ion profile']['extracellular K+ concentration'],
        configs['general options']['customized ion profile']['extracellular Cl- concentration'],
        configs['general options']['customized ion profile']['extracellular Ca2+ concentration'],
        configs['general options']['customized ion profile']['extracellular protein- concentration'],
        configs['general options']['customized ion profile']['cytosolic Na+ concentration'],
        configs['general options']['customized ion profile']['cytosolic K+ concentration'],
        configs['general options']['customized ion profile']['cytosolic Cl- concentration'],
        configs['general options']['customized ion profile']['cytosolic Ca2+ concentration'],
        configs['general options']['customized ion profile']['cytosolic protein- concentration'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_Na'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_K'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_Cl'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_Ca'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_M'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_P'],
        int(configs['change K env']['event happens']),
        configs['change K env']['change start'],
        configs['change K env']['change finish'],
        configs['change K env']['change rate'],
        configs['change K env']['multiplier'],
        int(configs['change Cl env']['event happens']),
        configs['change Cl env']['change start'],
        configs['change Cl env']['change finish'],
        configs['change Cl env']['change rate'],
        configs['change Cl env']['multiplier'],
        int(configs['change Na env']['event happens']),
        configs['change Na env']['change start'],
        configs['change Na env']['change finish'],
        configs['change Na env']['change rate'],
        configs['change Na env']['multiplier'],
        int(configs['change temperature']['event happens']),
        configs['change temperature']['change start'],
        configs['change temperature']['change finish'],
        configs['change temperature']['change rate'],
        configs['change temperature']['multiplier'],
        int(configs['block gap junctions']['event happens']),
        configs['block gap junctions']['change start'],
        configs['block gap junctions']['change finish'],
        configs['block gap junctions']['change rate'],
        configs['block gap junctions']['random fraction'],
        int(configs['block NaKATP pump']['event happens']),
        configs['block NaKATP pump']['change start'],
        configs['block NaKATP pump']['change finish'],
        configs['block NaKATP pump']['change rate']
    ]