
def encodeConfigs(configs):
    return [
        configs['sim time settings']['time step'],
        configs['sim time settings']['total time'],
        configs['sim time settings']['sampling rate'],
        configs['general options']['customized ion profile']['extracellular Na+ concentration'],
        configs['general options']['customized ion profile']['extracellular K+ concentration'],
        configs['general options']['customized ion profile']['extracellular Cl- concentration'],
        configs['general options']['customized ion profile']['extracellular Ca2+ concentration'],
        configs['general options']['customized ion profile']['extracellular protein- concentration'],
        configs['general options']['customized ion profile']['cytosolic Na+ concentration'],
        configs['general options']['customized ion profile']['cytosolic K+ concentration'],
        configs['general options']['customized ion profile']['cytosolic Cl- concentration'],
        configs['general options']['customized ion profile']['cytosolic Ca2+ concentration'],
        configs['general options']['customized ion profile']['cytosolic protein- concentration'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_Na'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_K'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_Cl'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_Ca'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_M'],
        configs['tissue profile definition']['tissue']['default']['diffusion constants']['Dm_P'],
        configs['tissue profile definition']['tissue']['profiles'][0]['diffusion constants']['Dm_Na'],
        configs['tissue profile definition']['tissue']['profiles'][0]['diffusion constants']['Dm_K'],
        configs['tissue profile definition']['tissue']['profiles'][0]['diffusion constants']['Dm_Cl'],
        configs['tissue profile definition']['tissue']['profiles'][0]['diffusion constants']['Dm_Ca'],
        configs['tissue profile definition']['tissue']['profiles'][0]['diffusion constants']['Dm_M'],
        configs['tissue profile definition']['tissue']['profiles'][0]['diffusion constants']['Dm_P'],
        int(configs['change Na mem']['event happens']),
        configs['change Na mem']['change start'],
        configs['change Na mem']['change finish'],
        configs['change Na mem']['change rate'],
        configs['change Na mem']['multiplier']
    ]